nl-design-system/gebruikersonderzoeken

docs/onderzoek-bekijken/utrecht-informatiecampagne-18-jaar.md
=> Voeg onderzoek toe voor informatiecampage 18 jaar

docs/onderzoek-bekijken/utrecht-google-translate.md
Google translate research toegevoegd
=> docs: google translate onderzoek toegevoegd

docs/onderzoek-bekijken/utrecht-google-translate.md
Doc type and link to bijlages added
=> docs(fix): doc type and link to bijlages

docs/onderzoek-bekijken/mijn-zaken/_category_.json, docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
onderzoek naar generieke services toegevoegd.
=> Mijn den haag

docs/onderzoek-bekijken/utrecht-dark-mode.md, docs/onderzoek-bekijken/utrecht-google-translate.md
Dark mode onderzoek staat klaar voor publicatie
=> Dark-mode-onderzoek

docs/onderzoek-bekijken/valsplat-corona.md
Onderzoek van Paul van Sommeren toegevoegd
=> docs: onderezoek mvoc toegevoegd

docs/onderzoek-bekijken/utrecht-gehandicaptenparkeerkaart.md, docs/onderzoek-bekijken/utrecht-initiatieven.md, docs/onderzoek-bekijken/utrecht-verhuisaangiften.md
Korte referenties naar stadskamer toegevoegd op aanvraag van Sandra Deckers.
=> docs: stadskamer ref

.npmrc, docusaurus.config.js, package.json, pnpm-lock.yaml
Closes https://github.com/nl-design-system/gebruikersonderzoeken/issues/35
=> feat: add mvp version of search with Algolia

docs/onderzoek-bekijken/wmebv/_category_.json, docs/onderzoek-bekijken/wmebv/vng-online-formulieren.md
https://gebruikersonderzoeken-git-docs-add-wmebv-test1-nl-design-system.vercel.app/docs/onderzoek-bekijken/wmebv/vng-online-formulieren?_vercel_share=CjXSGeneK3adCoD1y63hAmOFQSX9vHgR
=> docs: add wmebv rapport

package.json, pnpm-lock.yaml
There were no new major versions.
=> build: patch round 2024-02

package.json, pnpm-lock.yaml
- install patch updates
- install minor updates
- no major updates
=> build: patch round 2024-05

README.md, docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md, docs/onderzoek-bekijken/18-jaar worden/utrecht-informatiecampagne-18-jaar.md, docs/onderzoek-bekijken/iconen/utrecht-bevrijdingsdag.md, docs/onderzoek-bekijken/iconen/utrecht-februari-2023.md, docs/onderzoek-bekijken/iconen/utrecht-november-2022.md, docs/onderzoek-bekijken/iconen/utrecht-parkeer-icoon.md, docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md, docs/onderzoek-bekijken/mijn-zaken/utrecht-status-component.md, docs/onderzoek-bekijken/utrecht-gehandicaptenparkeerkaart.md, docs/onderzoek-bekijken/valsplat-corona.md, docs/onderzoek-bekijken/website-gebruik/utrecht-dark-mode.md, docs/onderzoek-bekijken/website-gebruik/utrecht-google-translate.md, docs/onderzoek-bekijken/wmebv/vng-online-formulieren.md
Voor het toevoegen van plaatjes op een plek waar we controle over hebben gebruiken we bij nldesignsystem.nl een losse `assets` branch.
Met de GitHub UI kun je daar plaatjes uploaden die je vervolgens kan gebruiken in markdown. Hieronder de beschrijving van hoe dit werkt, zoals deze ook toegevoegd is in de README.md
---
Plaatjes zijn heel groot om via GitHub heen en weer te sturen. Daarom gebruiken we de [assets branch](https://github.com/nl-design-system/gebruikersonderzoeken/tree/assets) om plaatjes te uploaden. Deze kunnen vervolgens als plaatje in markdown worden gezet, zoals bijvoorbeeld:
```md
```
Voor de naam van het bestand gebruik je `<naam van het markdown bestand>__<plek in de markdown>` bijvoorbeeld:
```md
```
=> refactor: add images from new assets branch

.github/workflows/continuous-deployment.yml
=> build: add missing hash

docs/onderzoek-bekijken/2-mijn-zaken/acato-exploratief-onderzoek.md
=> Profielservice onderzoek toegevoegd

docs/onderzoek-bekijken/6-corona/1-valsplat-corona-mijn-vraag-over-corona.md, docs/onderzoek-bekijken/6-corona/2-valsplat-corona-prototype-mijn-vraag-over-corona.md, docs/onderzoek-bekijken/6-corona/3-valsplat-corona-kwetsbaren.md, docs/onderzoek-bekijken/6-corona/4-valsplat-corona-cardsort-mijn-vraag-over-corona.md, docs/onderzoek-bekijken/6-corona/5-valsplat-corona-straatonderzoek-afschalen-maatregelen.md, docs/onderzoek-bekijken/utrecht-initiatieven.md, docs/onderzoek-delen/README.md, docs/onderzoek-delen/_onderzoek-template.md
Logius overweegt om gebruikersonderzoeken te delen en het leek me handig om de template dan beschikbaar te maken.
Daarnaast is valsplat akkoord met het publiceren onder CC0
=> docs: delen makkelijker maken en cc0 valsplat

docs/onderzoek-bekijken/2-mijn-zaken/vng-profiel-service-omnichannel.md
Via Slack in markdown aangeleverd door Rico van der Sloot
> Hi zouden jullie de uitkomsten van het UX onderzoek voor Mijn Profielservice online willen zetten? Ik heb hier weer een markdown file van het onderzoek.
[Uitkomsten UX onderzoek Mijn Profiel Service Omnichannel.md](https://github.com/user-attachments/files/16539446/Uitkomsten.UX.onderzoek.Mijn.Profiel.Service.Omnichannel.md)
=> docs: uitkomsten UX onderzoek Mijn Profiel Service Omnichannel

docs/onderzoek-bekijken/2-mijn-zaken/vng-profielservice/_category_.json, docs/onderzoek-bekijken/2-mijn-zaken/vng-profielservice/vng-profielservice-exploratief-onderzoek.md, docs/onderzoek-bekijken/2-mijn-zaken/vng-profielservice/vng-profielservice-omnichannel.md
Op verzoek van Rico een groepering van de profielservice onderzoeken
=> docs: group profileservice rapports

.husky/pre-commit, .lintstagedrc.json, lint-staged.config.cjs, package.json, pnpm-lock.yaml
- install patch, minor, and major updates
- fix husky's pre-commit hook
- add lint-staged and run everything through Prettier
=> build: patch round 2024-09

docs/onderzoek-bekijken/2-mijn-zaken/vng-mijn-producten/_category_.json, docs/onderzoek-bekijken/2-mijn-zaken/vng-mijn-producten/vng-mijn-producten-exploratief-onderzoek.md
https://github.com/nl-design-system/gebruikersonderzoeken/issues/278
=> feat: add mijn producten exploratief onderzoek van vng

docs/onderzoek-bekijken/2-mijn-zaken/vng-mijn-producten/vng-mijn-producten-exploratief-onderzoek.md
based on the reviews of Rozerin in PR #279
=> fix: improve mijn producten page

.ncurc.major.cjs
@docsearch/react needs to be updated before we can update to React 19
Closes #290
=> chore: update npm-check-updates config

docs/onderzoek-bekijken/1-formulieren/samenwerking-klachtenformulier-onderzoek.md
=> onderzoek klachtenformulier toegevoegd

docs/onderzoek-bekijken/2-mijn-zaken/denhaag-mijn-producten.md
Vervolgonderzoek op mijn producten van Den Haag versie 1. Mogelijk nog plaatjes toevoegen, maar de content staat er in ieder geval.
=> doc: vervolgonderzoek mijn producten toegevoegd

docs/onderzoek-bekijken/4-website-gebruik/utrecht-lettertype.md
onderzoek naar lettertype met neurodiversiteitsnetwerk
=> Utrecht-lettertype

packages/website/package.json, packages/website/tsconfig.json, pnpm-lock.yaml
=> TypeScript met strikte instellingen

packages/website/src/layouts/default.tsx, packages/website/src/utils/csp.ts, packages/website/tsconfig.json, packages/website/vercel.json
=> Add CSP headers

packages/website/package.json, packages/website/src/components/breadcrumb/breadcumb.tsx, packages/website/src/layouts/default.astro, packages/website/src/pages/docs/[...id].astro, packages/website/src/utils/menu/index.ts, packages/website/tsconfig.json, pnpm-lock.yaml
=> Bread crumb

packages/website/src/content.config.ts, packages/website/src/pages/docs/[...id].astro, packages/website/src/utils/menu/_build-menu-structure.ts, packages/website/src/utils/menu/index.ts, packages/website/src/utils/menu/to-clean-route.ts
=> [FIX]: Urls komen niet overeen met Docusaurus

docs/onderzoek-bekijken/4-website-gebruik/utrecht-lettertype.md, docs/onderzoek-bekijken/tilburg-publicatieportaal.md
Onderzoek van de gemeente Tilburg naar de publicatie portal toegevoegd.
=> (docs): onderzoek tilburg toegevoegd

packages/ma-components/local/navigation-bar/navigation-bar.css, packages/ma-components/local/navigation-bar/navigation-bar.tsx, packages/ma-components/local/site-footer/site-footer.css, packages/ma-components/local/site-header/site-header.css, packages/ma-components/local/site-header/site-header.tsx, packages/website/package.json, packages/website/src/layouts/default.astro, packages/website/src/layouts/default.css, pnpm-lock.yaml
Het `NavigationBar` component
De refactor van `SiteHeader` is niet heel erg optimaal, maar er komt een issue aan (#384) die de `SiteHeader` netjes maakt. Deze PR is dus puur bedoeld om de `NavigationBar` te bouwen volgens [de spec](https://www.figma.com/design/M8Uy7pOdhOOoOvbmwyFHaa/Local-Bibliotheek---Mooi---Anders?node-id=9963-2846&m=dev) in Figma.
closes: #401
=> feat: navigation bar component

_themes/content-en-begrijpelijkheid.md, _themes/formulieren.md, _themes/navigatie-en-structuur.md, _themes/overig.md, docs/onderzoek-bekijken/1-formulieren/samenwerking-klachtenformulier-onderzoek.md, docs/onderzoek-bekijken/1-formulieren/utrecht-klachtenformulier-onderzoek.md, docs/onderzoek-bekijken/1-formulieren/vng-online-formulieren.md, packages/website/src/content.config.ts, packages/website/src/pages/docs/[...id].astro, packages/website/src/pages/docs/[...path].astro, packages/website/src/pages/docs/onderzoek-bekijken.astro, packages/website/src/pages/docs/onderzoek-bekijken/[...id].astro, packages/website/src/pages/docs/thema/[...theme].astro, packages/website/src/pages/docs/thema/index.astro, packages/website/src/utils/menu/to-clean-route.ts, packages/website/src/utils/themes.ts
=> Introduce themes as a concept

packages/website/src/components/theme-list/theme-list.tsx, packages/website/src/layouts/center-column.css, packages/website/src/pages/docs/onderzoek-bekijken/[...id].astro
=> Onderzoek pages have a link back to the themes

packages/ma-components/local/tag/tag.css, packages/ma-components/local/tag/tag.tsx, packages/website/src/components/theme-list/theme-list.css, packages/website/src/components/theme-list/theme-list.tsx
=> feat: add ma-components/tag component

docs/privacyverklaring/README.md, packages/website/src/components/gebruikersonderzoeken-footer/gebruikersonderzoeken-footer.tsx
=> Remove non existing links from footer

packages/ma-components/local/banner/banner.css, packages/ma-components/local/banner/banner.tsx, packages/website/package.json, packages/website/src/assets/styles.css, packages/website/src/components/hero/hero.tsx, packages/website/src/pages/index.astro, pnpm-lock.yaml
=> Banner component

_themes/content-en-begrijpelijkheid.md, _themes/formulieren.md, _themes/navigatie-en-structuur.md, _themes/overig.md, packages/ma-components/local/card-as-link/card-as-link.css, packages/ma-components/local/card-as-link/card-as-link.tsx, packages/ma-components/local/card-list/card-list.css, packages/ma-components/local/card-list/card-list.tsx, packages/website/src/components/card-list-onderzoek/card-list-onderzoek.tsx, packages/website/src/components/card-list-theme/card-list-theme.tsx, packages/website/src/content.config.ts, packages/website/src/layouts/center-column.css, packages/website/src/pages/docs/onderzoek-bekijken.astro, packages/website/src/pages/docs/thema/[...theme].astro, packages/website/src/pages/docs/thema/[...theme].css
closes: #421
closes: #425
closes: #435
closes: #433
=> Card As Link component

packages/ma-components/local/navigation-drawer/navigation-drawer.css, packages/ma-components/local/navigation-drawer/navigation-drawer.tsx, packages/ma-components/local/toolbar-button/toolbar-button.css, packages/ma-components/local/toolbar-button/toolbar-button.tsx, packages/website/package.json, packages/website/src/assets/styles.css, packages/website/src/components/gebruikersonderzoeken-header/gebruikersonderzoeken-header.css, packages/website/src/components/gebruikersonderzoeken-header/gebruikersonderzoeken-header.tsx, packages/website/src/components/gebruikersonderzoeken-navigation-drawer/gebruikersonderzoeken-navigation-drawer.tsx, packages/website/src/layouts/default.astro, packages/website/vercel.json, pnpm-lock.yaml
Drawer is enkel te zien op klein scherm, door het openen van het Menu. De sluit knop is in Figma nog een todo component, dus die styling is niet af.
De design tokens zitten nog niet in de `ma-design-tokens` package. Zodra dat het geval is moeten de token definities uit de CSS gehaald worden
closes: #454
=> Navigation Drawer

docs/onderzoek-bekijken/1-formulieren/samenwerking-klachtenformulier-onderzoek.md, packages/website/src/content.config.ts, packages/website/src/pages/docs/onderzoek-bekijken/[...id].astro
=> Summary on onderzoekspage

packages/website/src/pages/docs/onderzoek-bekijken.astro, packages/website/src/pages/index.astro
=> Remove themes without onderzoeken from interface

docs/onderzoek-bekijken/2-mijn-zaken/denhaag-mijn-producten-2.md, docs/onderzoek-bekijken/2-mijn-zaken/vng-mijn-producten/vng-mijn-producten-exploratief-onderzoek.md, docs/onderzoek-bekijken/2-mijn-zaken/vng-profielservice/vng-profielservice-exploratief-onderzoek.md, docs/onderzoek-bekijken/2-mijn-zaken/vng-profielservice/vng-profielservice-omnichannel.md, docs/onderzoek-bekijken/6-corona/1-valsplat-corona-mijn-vraag-over-corona.md
=> Fix 404 links

packages/ma-components/page-header/page-header.css, packages/website/src/components/logo/logo.css, packages/website/src/components/page-section/page-section.css
=> Fix missing logo text

packages/website/astro.config.ts, packages/website/markdown-plugins/rehype-nlds-components/figure.ts, packages/website/markdown-plugins/rehype-nlds-components/index.ts, packages/website/markdown-plugins/remark-nlds-components/index.ts, packages/website/package.json, packages/website/src/assets/styles.css, pnpm-lock.yaml
=> Fix images in figures

docs/onderzoek-bekijken/1-formulieren/utrecht-klachtenformulier-onderzoek.md, docs/onderzoek-bekijken/3-iconen/utrecht-bevrijdingsdag.md, docs/onderzoek-bekijken/3-iconen/utrecht-februari-2023.md, docs/onderzoek-bekijken/3-iconen/utrecht-november-2022.md, docs/onderzoek-bekijken/3-iconen/utrecht-parkeer-icoon.md, docs/onderzoek-bekijken/4-website-gebruik/utrecht-dark-mode.md, docs/onderzoek-bekijken/4-website-gebruik/utrecht-google-translate.md, docs/onderzoek-bekijken/4-website-gebruik/utrecht-lettertype.md, docs/onderzoek-bekijken/7-beslisboom/utrecht-keuzehulp-geldhulp-beslisboom-1.md, docs/onderzoek-bekijken/7-beslisboom/utrecht-keuzehulp-geldhulp-beslisboom-2.md, docs/onderzoek-bekijken/utrecht-constateringsbrieven.md, docs/onderzoek-bekijken/utrecht-gehandicaptenparkeerkaart.md, docs/onderzoek-bekijken/utrecht-online-meldingen.md
**Toegevoegde key-info**
- target_group: inwoners van Utrecht
- type
- date_conducted
**Aangevulde onderzoeken:**
- [Nieuwe klachtenformulier Gemeente Utrecht](https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/formulieren/utrecht-klachtenformulier-onderzoek)
- [Onderzoek bevrijdingsdag, koningsdag en melding icoon](https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/iconen/utrecht-bevrijdingsdag)
- [Onderzoek iconen Februari 2023](https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/iconen/utrecht-februari-2023)
- [Onderzoek iconen November 2022](https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/iconen/utrecht-november-2022)
- [Onderzoek parkeer icoon](https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/iconen/utrecht-parkeer-icoon)
- [Dark mode gebruik op …
=> Key info update
